---
ID: "4db4624b-ae02-4361-b4db-289796e5254c"
Parent: "27d81862-4bc5-4ee7-ae05-d0da7eed4d47"
Template: "0117897e-28d7-4932-9402-6b71175cef11"
Path: /sitecore/system/Settings/Rules/Definitions/Demandbase/Levels/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161011T203006Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d8477e99-1ab3-4aeb-828f-2de82faa17ca"
      Hint: Value
      Value: 
